# Generated by Django 4.1 on 2022-12-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountmodel',
            name='emial',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
