# Generated by Django 4.1 on 2022-12-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccountmodel_emial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccountmodel',
            old_name='emial',
            new_name='email',
        ),
    ]
