# Generated by Django 4.1 on 2023-01-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_emial_useraccountmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountmodel',
            name='name',
        ),
    ]
