# Generated by Django 4.1 on 2023-01-09 18:06

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_useraccountmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountmodel',
            name='profile_image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=account.models.UserAccountModel.content_file_name),
        ),
    ]
