# Generated by Django 4.1 on 2023-02-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_useraccountmodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountmodel',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
