# Generated by Django 4.1 on 2022-11-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalmeaningmodel',
            name='meaning',
            field=models.JSONField(),
        ),
    ]
