# Generated by Django 4.1 on 2022-11-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbox', '0002_alter_globalmeaningmodel_meaning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalmeaningmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='globalmeaningmodel',
            name='word',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
