version: "3.9"
name: langpal_dev
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

    # command: gunicorn --bind 0.0.0.0:8000 langpal.wsgi:application
    # command: /bin/sh -c "entrypoint.sh"
    env_file:
      - .env
    # below for realtime edit. Convenient for develoment
    volumes:
      - .:/app
    depends_on:
      - db
      - redis_dev
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=langpalDB"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=spiderman" 
  redis_dev:
    container_name: 'redis_dev'
    image: redis:alpine
    ports: 
      - "6378:6379"
  


volumes:
  postgres_data_dev: