version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    # below for realtime edit. Convenient for develoment
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
  
  proxy:
    build:
      context: ./proxy
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=langpalDB"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=spiderman" 

  redis:
    container_name: 'redis'
    image: redis:alpine
    ports: 
      - "6378:6379"
  

volumes:
  static:
  media:
  postgres_data: