# Generated by Django 4.1 on 2022-11-08 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostmodel',
            name='posted_on',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
