# Generated by Django 4.1 on 2022-12-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefeed', '0002_alter_userpostmodel_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostmodel',
            name='image_post',
            field=models.ImageField(null=True, upload_to='posts/'),
        ),
    ]
