# Generated by Django 4.1 on 2022-12-25 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homefeed', '0004_userpostmodel_downvote_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostmodel',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PostVoteUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_as', models.CharField(max_length=5)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homefeed.userpostmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
