# Generated by Django 4.1 on 2022-12-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefeed', '0005_alter_userpostmodel_user_name_postvoteupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostmodel',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpostmodel',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
