# Generated by Django 4.1 on 2023-01-05 19:08

from django.db import migrations, models
import homefeed.models


class Migration(migrations.Migration):

    dependencies = [
        ('homefeed', '0006_alter_userpostmodel_downvote_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostmodel',
            name='image_post',
            field=models.ImageField(null=True, upload_to=homefeed.models.UserPostModel.content_file_name),
        ),
    ]
