# Generated by Django 4.1 on 2022-12-13 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContactPostModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('idea_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutIdeaPostModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('idea_text', models.TextField()),
            ],
        ),
    ]
