# Generated by Django 4.1 on 2023-01-07 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutContactPostModel',
        ),
        migrations.AddField(
            model_name='aboutideapostmodel',
            name='idea_title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='aboutideapostmodel',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
