# Generated by Django 4.1 on 2023-01-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_user_name_aboutideapostmodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutideapostmodel',
            old_name='username',
            new_name='user_name',
        ),
    ]
