# Generated by Django 4.1 on 2023-01-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_username_aboutideapostmodel_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutideapostmodel',
            name='idea_votes',
            field=models.IntegerField(default=0),
        ),
    ]
