# Generated by Django 4.1 on 2023-01-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomslist',
            name='coverimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chatroomslist',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
