# Generated by Django 4.1 on 2023-01-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_chatroomslist_coverimage_chatroomslist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='image_message',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
