# Generated by Django 4.1 on 2023-02-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_usermessage_image_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={},
        ),
    ]
