# Generated by Django 4.1 on 2023-02-09 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0005_alter_usermessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
