# Generated by Django 4.1 on 2023-02-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0006_alter_usermessage_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ('date_added',)},
        ),
    ]
